Add ability to use commit message on autocommits

diff --git a/scripts/autocommit b/scripts/autocommit
--- a/scripts/autocommit
+++ b/scripts/autocommit
@@ -34,6 +34,11 @@ testdir="${projectdir}/$1"
 
 if [[ $1 == "unroll" ]]; then
   if [[ $2 != '-f' ]]; then
+    if ! git diff-index --quiet HEAD; then
+      echo "Dirty Repo, aborting"
+      exit 1
+    fi
+
     echo "Linting"
     pushd "$projectdir" >/dev/null || exit 1
     golangci-lint run --out-format tab --new-from-rev $(squashHead) || exit
@@ -49,6 +54,7 @@ else
     exit 1
   fi
 
-  ginkgo watch --succinct --afterSuiteHook="${scriptdir}/commitOnPass.sh (ginkgo-suite-passed)" \
+  shift
+  ginkgo watch --succinct --afterSuiteHook="${scriptdir}/commitOnPass.sh (ginkgo-suite-passed) $*" \
     "${testdir}"
 fi
